import Link from "next/link";
import { dictionary, journey, tours, type Locale } from "@/lib/site-data";

export default async function Home({ params }: { params: Promise<{ locale: Locale }> }) { const { locale } = await params; const t = dictionary[locale]; const tour = tours[0]; const nl=locale==="nl"; const copy=nl?{duration:"Vanaf 2 dagen / 1 nacht. Blijf langer als je meer tijd op het water wilt.",location:"Brokopondo-stuwmeer",level:"Beginner tot ervaren",price:"Prijs op aanvraag",cta:"Klaar om de stad achter je te laten?",eyebrow:"Verder dan de oever"}:{duration:"From 2 days / 1 night. Stay longer when you want more time on the water.",location:"Brokopondo Reservoir",level:"Beginner to experienced",price:"Price on request",cta:"Ready to leave the city behind?",eyebrow:"Go beyond the shore"}; return <main>
  <section className="hero"><div className="hero-media" role="img" aria-label="Boat on Brokopondo Reservoir"/><div className="hero-shade"/><div className="shell hero-content"><h1>{t.hero.title.split("\n").map((x) => <span key={x}>{x}</span>)}</h1><p className="hero-copy">{t.hero.copy}</p><div className="hero-actions"><Link className="button" href={`/${locale}/tours/${tour.slug}`}>{t.hero.explore}</Link><Link className="text-link light" href={`/${locale}/book`}>{t.hero.plan}</Link></div></div><div className="hero-facts shell"><span>{nl?"Vanaf 2 dagen":"From 2 days"}</span><span>{nl?"Lokale gidsen":"Local guides"}</span><span>{nl?"Kleine groepen":"Small groups"}</span><span>{nl?"Ophalen inbegrepen":"Pickup included"}</span></div></section>
  <section id="experience" className="section intro-section"><div className="shell editorial-split"><div><p className="eyebrow">{t.home.introEyebrow}</p><h2>{t.home.introTitle}</h2></div><div className="intro-copy"><p>{t.home.introCopy}</p><p className="quiet">No rush to turn back before the story starts.</p></div></div></section>
  <section className="journey-section"><div className="shell"><p className="eyebrow">{t.home.journeyEyebrow}</p><div className="section-heading"><h2>{t.home.journeyTitle}</h2><span className="line"/></div><ol className="journey-list">{journey[locale].map(([number,title,copy]) => <li key={number}><span className="journey-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol></div></section>
  <section className="section featured-tour"><div className="shell tour-feature-grid"><div className="tour-photo" role="img" aria-label="Brokopondo Reservoir fishing expedition"/><div className="tour-feature-copy"><p className="eyebrow">{t.home.tourEyebrow}</p><h2>{t.home.tourTitle}</h2><p className="lead">{copy.duration} {nl?"Je vertrekt vanuit Paramaribo, vaart Brokopondo in en slaapt vlak bij het water.":"Start in Paramaribo, travel by boat into Brokopondo and sleep close to the water."}</p><div className="tour-meta"><span>{copy.location}</span><span>{copy.level}</span><span>{copy.price}</span></div><div className="action-row"><Link className="button" href={`/${locale}/book`}>{t.home.request}</Link><Link className="text-link" href={`/${locale}/tours/${tour.slug}`}>{t.home.details}</Link></div></div></div></section>
  <section className="island-banner"><div className="shell island-inner"><div><p className="eyebrow light">{t.home.islandEyebrow}</p><h2>{t.home.islandTitle}</h2><p>{t.home.islandCopy}</p><Link className="text-link light" href={`/${locale}/sodjo-island`}>{t.home.islandLink}</Link></div><div className="island-coordinates"><span>Brokopondo Reservoir</span><small>Approximate area</small></div></div></section>
  <section className="closing-cta"><div className="shell"><p className="eyebrow">{copy.eyebrow}</p><h2>{copy.cta}</h2><Link className="button" href={`/${locale}/book`}>{t.nav.book}</Link></div></section>
</main>; }
